#!/bin/bash

# Update dependencies
sudo apt-get update -y
sudo apt-get install software-properties-common -y
sudo add-apt-repository universe -y
sudo add-apt-repository ppa:certbot/certbot -y
sudo apt-get update -y

# Install certbot
sudo apt-get install certbot python-certbot-nginx -y

# Start certbot
sudo certbot --nginx
