#!/bin/bash

# Install neovim

if ! sudo apt-get install neovim; then
  sudo add-apt-repository ppa:neovim-ppa/stable
  sudo apt-get update
  sudo apt-get install neovim
fi

# Install vim-plug
curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

mkdir ~/.config/nvim -p 

# Configure neovim
# DONT FORGET TO DO :PlugInstall
cat <<HERE > ~/.config/nvim/init.vim
set tabstop     =2
set softtabstop =2
set shiftwidth  =2
set expandtab

" Plugins will be downloaded under the specified directory.
call plug#begin('~/.config/nvim/plugged')

" Declare the list of plugins.
Plug 'dracula/vim', { 'as': 'dracula' }

" List ends here. Plugins become visible to Vim after this call.
call plug#end()

set termguicolors
colorscheme dracula
HERE

# Add aliases
echo "alias vim='nvim'" >> ~/.bashrc
echo "alias sudo='sudo '" >> ~/.bashrc
